FROM rust:1-bullseye AS builder
WORKDIR /home/echo-server

RUN apt-get update \
    && apt-get install -y protobuf-compiler

COPY ./ /home/echo-server/opentelemetry-rust-contrib/

WORKDIR /home/echo-server/opentelemetry-rust-contrib/opentelemetry-instrumentation-tower/examples/hyper-http-service
RUN cargo build --locked --release --target-dir ./target

FROM debian:bullseye-slim

COPY --from=builder /home/echo-server/opentelemetry-rust-contrib/opentelemetry-instrumentation-tower/examples/hyper-http-service/target/release/example-hyper-http-service /usr/local/bin/http-server
CMD ["http-server"]