name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage:todo"]
projects: ["open-telemetry/opentelemetry-rust-contrib"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: api-version
    attributes:
      label: API Version
      description: What version of the OpenTelemetry API are you using?
      placeholder: 0.x, 1.x, etc.
    validations:
      required: true
  - type: textarea
    id: sdk-version
    attributes:
      label: SDK Version
      description: What version of the OpenTelemetry SDK are you using?
      placeholder: 0.x, 1.x, etc.
    validations:
      required: true
  - type: dropdown
    id: components
    attributes:
      label: What component are you working with?
      multiple: true
      options:
        - opentelemetry-aws
        - opentelemetry-contrib
        - opentelemetry-datadog
        - opentelemetry-dynatrace
        - opentelemetry-etw-logs
        - opentelemetry-stackdriver
        - opentelemetry-user-events-logs
        - opentelemetry-user-events-metrics
        - opentelemetry-resource-detectors
        - N/A
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0
