use exporter::UserEventsSpanExporter;
use opentelemetry::otel_warn;
use opentelemetry_sdk::trace::TracerProviderBuilder;
use reentrant_spanprocessor::ReentrantSpanProcessor;

mod exporter;
mod reentrant_spanprocessor;

/// Extension trait for adding a user event span exporter to the tracer provider builder.
///
/// See the [crate-level documentation](crate) for details on resource attribute
/// mapping and well-known span attributes.
pub trait UserEventsTracerProviderBuilderExt {
    /// Adds a user event span exporter to the tracer provider builder with the given provider name.
    ///
    /// The provider name must:
    /// - Be less than 234 characters.
    /// - Contain only ASCII letters, digits, and the underscore (`'_'`) character.
    /// - Be short, human-readable, and unique enough to avoid conflicts with other provider names.
    /// - Typically include a company name and a component name, e.g., "MyCompany_MyComponent".
    ///
    /// If an invalid provider name is provided, this method will not add the exporter to the builder.
    ///
    /// # Tracepoint Names
    ///
    /// Tracepoint names are generated by combining the provider name, event
    /// level and keyword (currently hardcoded to `1`) in the following format:
    /// `ProviderName + '_' + 'L' + EventLevel + 'K' + EventKeyword`
    ///
    /// The EventLevel is always 4 (Informational) for Spans and the EventKeyword is always 1.
    /// For example, if "myprovider" is the provider name, the following tracepoint name is created:
    /// - `myprovider_L4K1`
    ///
    /// The `perf` tool can be used to record events from the tracepoints:
    /// ```sh
    /// perf record -e user_events:myprovider_L4K1
    /// ```
    ///
    /// # Resource Mapping
    ///
    /// The exporter reads `service.name` and `service.instance.id` from the
    /// [`Resource`](opentelemetry_sdk::Resource) and writes them as
    /// `ext_cloud_role` and `ext_cloud_roleInstance` in the exported event.
    fn with_user_events_exporter(self, provider_name: &str) -> Self;
}

impl UserEventsTracerProviderBuilderExt for TracerProviderBuilder {
    fn with_user_events_exporter(self, provider_name: &str) -> Self {
        match UserEventsSpanExporter::new(provider_name) {
            Ok(exporter) => {
                let reentrant_processor = ReentrantSpanProcessor::new(exporter);
                self.with_span_processor(reentrant_processor)
            }
            Err(e) => {
                otel_warn!(name: "User_Events.Exporter.CreationFailed", reason = &e);
                self
            }
        }
    }
}
