name: ETW Integration

env:
  CI: true

permissions:
  contents: read

on:
  pull_request:
    paths:
      - 'opentelemetry-etw-logs/**'
      - 'opentelemetry-etw-metrics/**'
      - 'opentelemetry-etw-traces/**'
      - 'Cargo.toml'
      - '.github/workflows/etw.yml'
  merge_group:
  push:
    branches:
      - main
    paths:
      - 'opentelemetry-etw-logs/**'
      - 'opentelemetry-etw-metrics/**'
      - 'opentelemetry-etw-traces/**'
      - 'Cargo.toml'
      - '.github/workflows/etw.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  etw-integration-test:
    runs-on: windows-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: true
    - uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88
      with:
        toolchain: stable
        components: llvm-tools-preview
    - name: cargo install cargo-llvm-cov
      uses: taiki-e/install-action@16b05812d776ae1dfaabc8277e421fb6d2506419 # v2.82.7
      with:
        tool: cargo-llvm-cov
    - name: Run ETW integration tests (logs)
      run: cargo llvm-cov --no-report --manifest-path opentelemetry-etw-logs/Cargo.toml --all-features -- --ignored --nocapture --test-threads=1
    - name: Run ETW integration tests (metrics)
      run: cargo llvm-cov --no-report --manifest-path opentelemetry-etw-metrics/Cargo.toml --all-features -- --ignored --nocapture --test-threads=1
    - name: Run ETW integration tests (traces)
      run: cargo llvm-cov --no-report --manifest-path opentelemetry-etw-traces/Cargo.toml --all-features -- --ignored --nocapture --test-threads=1
    - name: Generate lcov report
      run: cargo llvm-cov report --lcov --output-path lcov.info
    - name: Upload to codecov.io
      uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6.0.2
      with:
        files: lcov.info
        flags: etw-integration
        fail_ci_if_error: false
