name: PR Conventional Commit Validation

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  merge_group:

jobs:
  validate-pr-title:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: PR Conventional Commit Validation
        uses:  ytanikin/pr-conventional-commits@fda730cb152c05a849d6d84325e50c6182d9d1e9 # 1.5.1
        with:
          task_types: '["build","chore","ci","docs","feat","fix","perf","refactor","revert","test"]'
          add_label: 'false'
