[package]
name = "actix-web-opentelemetry"
version = "0.21.0"
description = "OpenTelemetry integration for Actix Web apps"
homepage = "https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main/actix-web-opentelemetry"
repository = "https://github.com/open-telemetry/opentelemetry-rust-contrib/tree/main/actix-web-opentelemetry"
readme = "README.md"
categories = ["api-bindings"]
keywords = ["actix", "actix-web", "opentelemetry", "jaeger", "prometheus"]
license = "Apache-2.0"
edition = "2021"
rust-version = "1.75.0"

[features]
metrics = ["opentelemetry/metrics"]
metrics-prometheus = [
  "metrics",
  "opentelemetry-prometheus",
  "prometheus",
  "dep:opentelemetry_sdk",
  "dep:tracing",
]
sync-middleware = []

[dependencies]
actix-http = { version = "3.0", default-features = false, features = [
  "compress-zstd",
] }
actix-web = { version = "4.0", default-features = false, features = [
  "compress-zstd",
] }
awc = { version = "3.0", optional = true, default-features = false, features = [
  "compress-zstd",
] }
futures-util = { version = "0.3", default-features = false, features = [
  "alloc",
] }
opentelemetry = { version = "0.28", default-features = false, features = [
  "trace",
] }
opentelemetry-prometheus = { version = "0.28", optional = true }
opentelemetry-semantic-conventions = { version = "0.28", features = [
  "semconv_experimental",
] }
opentelemetry_sdk = { version = "0.28", optional = true, features = [
  "metrics",
  "rt-tokio-current-thread",
] }
prometheus = { version = "0.13", default-features = false, optional = true }
serde = "1.0"
tracing = { version = "0.1.41", optional = true }

[dev-dependencies]
actix-web = { version = "4.0", features = ["macros"] }
actix-web-opentelemetry = { path = ".", features = [
  "metrics-prometheus",
  "sync-middleware",
  "awc",
] }
opentelemetry_sdk = { version = "0.28", features = [
  "spec_unstable_metrics_views",
  "metrics",
  "rt-tokio-current-thread",
] }
opentelemetry-otlp = { version = "0.28", features = ["grpc-tonic"] }
opentelemetry-stdout = { version = "0.28", features = ["trace", "metrics"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
